#!/usr/bin/env node
/**
 * Build script — bundles src/*.ts into a single distributable file.
 *
 * Output: dist/holographic-memory.ts
 *
 * OpenCode loads plugins as individual .ts files from ~/.config/opencode/plugins/.
 * Multi-file imports (./store, ./hrr, etc.) don't resolve there, so we bundle
 * everything into one self-contained file.
 */

const { readFileSync, writeFileSync, mkdirSync } = require('fs')
const { join, dirname } = require('path')

const ROOT = join(__dirname, '..')
const SRC = join(ROOT, 'src')
const DIST = join(ROOT, 'dist')

/** Files in dependency order (types first, entry last) */
const FILES = [
  'types.ts',
  'hrr.ts',
  'entities.ts',
  'store.ts',
  'retrieval.ts',
  'serialize.ts',
  'holographic-memory.ts',
]

/** Import lines to strip (inter-file imports that won't resolve in bundled form) */
const STRIP_IMPORTS = [
  /^import\s+\{[^}]+\}\s+from\s+['"]\.\/types['"];?\s*$/gm,
  /^import\s+\{[^}]+\}\s+from\s+['"]\.\/hrr['"];?\s*$/gm,
  /^import\s+\{[^}]+\}\s+from\s+['"]\.\/entities['"];?\s*$/gm,
  /^import\s+\{[^}]+\}\s+from\s+['"]\.\/store['"];?\s*$/gm,
  /^import\s+\{[^}]+\}\s+from\s+['"]\.\/retrieval['"];?\s*$/gm,
  /^import\s+\{[^}]+\}\s+from\s+['"]\.\/serialize['"];?\s*$/gm,
  /^import\s+\*\s+as\s+\w+\s+from\s+['"]\.\/hrr['"];?\s*$/gm,
  /^import\s+type\s+\{[^}]+\}\s+from\s+['"]\.\/types['"];?\s*$/gm,
  /^import\s+type\s+\{[^}]+\}\s+from\s+['"]\.\/store['"];?\s*$/gm,
  /^import\s+type\s+\{[^}]+\}\s+from\s+['"]\.\/retrieval['"];?\s*$/gm,
]

const HEADER = `// Holographic Memory — OpenCode Plugin (Bundled)
// Faithful port from Hermes Agent (NousResearch/hermes-agent)
// Compatible with @opencode-ai/plugin v1.14.x
//
// AUTO-GENERATED by scripts/build.js — do not edit manually.
// Source files: src/types.ts, src/hrr.ts, src/entities.ts, src/store.ts, src/retrieval.ts, src/serialize.ts, src/holographic-memory.ts
`

/** Match ALL import lines (external + inter-file) */
const IMPORT_RE = /^(import\s+(?:type\s+)?(?:\{[^}]*\}|\*\s+as\s+\w+)\s+from\s+['"][^'"]+['"];?\s*)$/gm

/** Match inter-file import sources */
const INTER_FILE_RE = /from\s+['"]\.\/(types|hrr|entities|store|retrieval|serialize|holographic-memory)['"]/;

function stripInterFileImports(content) {
  let result = content
  for (const pattern of STRIP_IMPORTS) {
    result = result.replace(pattern, '')
  }
  return result
}

/** Replace `hrr.functionName(` with `functionName(` — namespace calls resolve to standalone exports */
function stripHrrNamespace(content) {
  return content.replace(/\bhrr\./g, '')
}

/** Extract external import lines from a file, deduplicate by source+names */
function extractImports(content) {
  const imports = []
  for (const match of content.matchAll(IMPORT_RE)) {
    const line = match[1].trim()
    if (!INTER_FILE_RE.test(line)) {
      imports.push(line)
    }
  }
  return imports
}

/** Deduplicate import lines by source module, preserving type-only imports */
function deduplicateImports(allImports) {
  const bySource = new Map()
  for (const line of allImports) {
    const srcMatch = line.match(/from\s+['"]([^'"]+)['"]/)
    if (!srcMatch) continue
    const src = srcMatch[1]
    // Extract imported names
    const namesMatch = line.match(/import\s+(?:type\s+)?\{([^}]+)\}/)
    if (!namesMatch) continue
    const names = namesMatch[1].split(',').map(n => n.trim()).filter(Boolean)
    if (!bySource.has(src)) {
      bySource.set(src, { typeNames: new Set(), valueNames: new Set() })
    }
    const entry = bySource.get(src)
    const isTypeImport = line.startsWith('import type')
    for (const n of names) {
      const hasInlineType = n.startsWith('type ')
      const clean = n.replace(/^type\s+/, '')
      if (isTypeImport || hasInlineType) {
        entry.typeNames.add(clean)
      } else {
        entry.valueNames.add(clean)
      }
    }
  }
  // Rebuild import lines — separate type-only and value imports
  const result = []
  for (const [src, { typeNames, valueNames }] of bySource) {
    // Remove any names that are in both sets (prefer type import for safety)
    for (const name of valueNames) {
      if (typeNames.has(name)) {
        valueNames.delete(name)
      }
    }
    // Emit value imports
    if (valueNames.size > 0) {
      const sorted = [...valueNames].sort()
      result.push(`import { ${sorted.join(', ')} } from '${src}'`)
    }
    // Emit type-only imports
    if (typeNames.size > 0) {
      const sorted = [...typeNames].sort()
      result.push(`import type { ${sorted.join(', ')} } from '${src}'`)
    }
  }
  return result
}

function build() {
  mkdirSync(DIST, { recursive: true })

  const allImports = []
  const sections = []

  for (const file of FILES) {
    const path = join(SRC, file)
    let content = readFileSync(path, 'utf-8')

    // Collect external imports before stripping
    allImports.push(...extractImports(content))

    // Strip all import lines (both inter-file and external)
    content = content.replace(IMPORT_RE, '')
    // Also strip inter-file imports with older patterns as fallback
    content = stripInterFileImports(content)
    // Strip hrr namespace prefix (e.g. hrr.encodeFact → encodeFact)
    content = stripHrrNamespace(content)

    // Add section header
    sections.push(
      `\n// ${'═'.repeat(60)}\n// ${file}\n// ${'═'.repeat(60)}\n`
    )
    sections.push(content.trim())
    sections.push('') // blank line between sections
  }

  // Deduplicate and place all imports at top
  const imports = deduplicateImports(allImports)
  let bundled = [HEADER, '', ...imports, '', ...sections].join('\n')

  // Strip 'export' keyword from all declarations except the plugin entry point.
  // OpenCode's loader iterates ALL exports and calls each function — exported
  // classes (FactRetriever, HolographicStore) crash when called without `new`.
  // Only `export const server` should be visible to the loader.
  bundled = bundled.replace(
    /^export\s+(?!const\s+server\b)(?:async\s+)?(?:function|class|interface|type|const|let|var|enum)\s/gm,
    (match) => match.replace(/^export\s/, '')
  )

  const outPath = join(DIST, 'holographic-memory.ts')
  writeFileSync(outPath, bundled, 'utf-8')

  const lineCount = bundled.split('\n').length
  console.log(`✓ Bundled ${FILES.length} files → ${outPath} (${lineCount} lines)`)
}

build()
